[package]
name = "stationlang"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "unwind"

[dependencies]
clap = { version = "^4.5", features = ["derive"] }
rust_decimal = "1.36.0"
thiserror = { version = "^2.0" }

[dev-dependencies]
anyhow = { version = "^1.0", features = ["backtrace"] }
