[package]
name = "stationlang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5", features = ["derive"] }
quick-error = "2.0.1"
rust_decimal = "1.36.0"

[dev-dependencies]
anyhow = { version = "^1.0", features = ["backtrace"] }
