<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>StationeersSlang</AssemblyName>
    <Description>Slang Compiler Bridge</Description>
    <Version>0.7.3</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOsPlatform('Linux'))">
    <GameInstallDir>$(HOME)/.local/share/Steam/steamapps/common/Stationeers</GameInstallDir>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOsPlatform('Windows'))">
    <GameInstallDir>C:\Program Files (x86)\Steam\steamapps\common\Stationeers</GameInstallDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(STATIONEERS_DIR)' != ''">
    <GameInstallDir>$(STATIONEERS_DIR)</GameInstallDir>
  </PropertyGroup>

  <ItemGroup>
      <Reference Include="netstandard">
        <HintPath>$(GameInstallDir)/rocketstation_Data/Managed/netstandard.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>$(GameInstallDir)/BepInEx/core/BepInEx.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="0Harmony">
        <HintPath>$(GameInstallDir)/BepInEx/core/0Harmony.dll</HintPath>
        <Private>False</Private>
      </Reference>

      <Reference Include="UnityEngine">
        <HintPath>$(GameInstallDir)/rocketstation_Data/Managed/UnityEngine.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>$(GameInstallDir)/rocketstation_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>$(GameInstallDir)/rocketstation_Data/Managed/Assembly-CSharp.dll</HintPath>
        <Private>False</Private>
      </Reference>

      <Reference Include="IC10Editor.dll">
        <HintPath>./ref/IC10Editor.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="LaunchPadBooster.dll">
      <HintPath>$(GameInstallDir)/BepInEx/plugins/StationeersLaunchPad/LaunchPadBooster.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="StationeersMods.Interface.dll">
      <HintPath>$(GameInstallDir)/BepInEx/plugins/StationeersLaunchPad/StationeersMods.Interface.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../rust_compiler/target/x86_64-pc-windows-gnu/release/slang.dll">
      <LogicalName>slang_compiler.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
